//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raktar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolgozo
    {
        public string Vezetéknév { get; set; }
        public string Keresztnév { get; set; }
        public System.DateTime Szülidő { get; set; }
        public string Taj { get; set; }
        public string Adóazonosító { get; set; }
        public string Irsz { get; set; }
    
        public virtual Város Város { get; set; }
    }
}
