//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raktar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class firepenguinEntities : DbContext
    {
        public firepenguinEntities()
            : base("name=firepenguinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Raktár> Raktár { get; set; }
        public virtual DbSet<Város> Város { get; set; }
        public virtual DbSet<Dolgozo> Dolgozo { get; set; }
        public virtual DbSet<Termék> Termék { get; set; }
    }
}
